### ISSUE TITLE
Daily

### ISSUE THREAD

**Issue by saganull** [enpitut/enpit-kun#1]
Log a pic of daily meeting everyday

**Comment by saganull** [comment]
![zenbrush_20150805230901](https://cloud.githubusercontent.com/assets/12422276/9104974/57682cc0-3bc7-11e5-8dce-6685921e66ce.png)

**Comment by ug23** [comment]
てすと

2015-08-06 15:12 GMT+09:00 Satoshi Saga <notifications@github.com>:

> [image: zenbrush_20150805230901]
> <https://cloud.githubusercontent.com/assets/12422276/9104974/57682cc0-3bc7-11e5-8dce-6685921e66ce.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enpitut/enpit-kun/issues/1#issuecomment-128262179>.
>



-- 
筑波大学大学院システム情報工学研究科
コンピュータサイエンス専攻（高度IT専修）
今川 裕士
phone: 090-1490-2620
email: s1420608@u.tsukuba.ac.jp

**Comment by ug23** [comment]
てすと

2015-08-06 15:12 GMT+09:00 Satoshi Saga <notifications@github.com>:

> [image: zenbrush_20150805230901]
> <https://cloud.githubusercontent.com/assets/12422276/9104974/57682cc0-3bc7-11e5-8dce-6685921e66ce.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enpitut/enpit-kun/issues/1#issuecomment-128262179>.
>



-- 
--
◇==========================================◇
筑波大学大学院 システム情報工学研究科
コンピュータサイエンス専攻（高度IT専修）
今川 裕士
phone: 090-1490-2620 / email: using923@gmail.com
◇==========================================◇

**Comment by ug23** [comment]
テスト

​

2015年8月6日 15:59 Yuji Imagawa <using923@gmail.com>:

> てすと
>
> 2015-08-06 15:12 GMT+09:00 Satoshi Saga <notifications@github.com>:
>
>> [image: zenbrush_20150805230901]
>> <https://cloud.githubusercontent.com/assets/12422276/9104974/57682cc0-3bc7-11e5-8dce-6685921e66ce.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/enpitut/enpit-kun/issues/1#issuecomment-128262179>.
>>
>
>
>
> --
> --
> ◇==========================================◇
> 筑波大学大学院 システム情報工学研究科
> コンピュータサイエンス専攻（高度IT専修）
> 今川 裕士
> phone: 090-1490-2620 / email: using923@gmail.com
> ◇==========================================◇
>



-- 
--
◇==========================================◇
筑波大学大学院 システム情報工学研究科
コンピュータサイエンス専攻（高度IT専修）
今川 裕士
phone: 090-1490-2620 / email: using923@gmail.com
◇==========================================◇
